---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
# https://xsgames.co/randomusers/
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kkaluza
  description: Product Manager
spec:
  profile:
    displayName: Kirby Kaluza
    email: kirby@rhdh.com
    picture: /avatars/75.jpg
  memberOf: [rhdh-team, Product-Manager]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: clandsteiner
  description: Head of Product
spec:
  profile:
    displayName: Cherry Landsteiner
    email: cherry@rhdh.com
    picture: /avatars/19.jpg
  memberOf: [rhdh-team, Product-Manager]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lrita
  description: UX Designer
spec:
  profile:
    displayName: Lakenya Rita
    email: lakenya@rhdh.com
    picture: /avatars/32.jpg
  memberOf: [rhdh-team, UXD]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rlondino
  description: UX Designer
spec:
  profile:
    displayName: Ryan Londino
    email: ryan@rhdh.com
    picture: /avatars/0.jpg
  memberOf: [rhdh-team, UXD]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: skichline
  description: Software Engineer
spec:
  profile:
    displayName: Saran Kichline
    email: saran@rhdh.com
    picture: /avatars/54.jpg
  memberOf: [rhdh-team, Developers, Engineering]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rkauper
  description: Software Engineer
spec:
  profile:
    displayName: Raul Kauper
    email: raul@rhdh.com
    picture: /avatars/73.jpg
  memberOf: [rhdh-team, Developers, Engineering]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: msorkin
  description: Principal Software Engineer
spec:
  profile:
    displayName: Malcom Sorkin
    email: malcom@rhdh.com
    picture: /avatars/38.jpg
  memberOf: [rhdh-team, Developers, Engineering]
---
#51 - Gita Wallraff
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gwallraff
  description: Senior Software Engineer
spec:
  profile:
    displayName: Gita Wallraff
    email: gita@rhdh.com
    picture: /avatars/51.jpg
  memberOf: [rhdh-team, Developers, Engineering]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dokimura
  description: Software Quality Engineer
spec:
  profile:
    displayName: Darell Okimura
    email: darell@rhdh.com
    picture: /avatars/56.jpg
  memberOf: [rhdh-team, QE, Engineering]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jchama
  description: Software Quality Engineer
spec:
  profile:
    displayName: Jonas Chama
    email: jonas@rhdh.com
    picture: /avatars/8.jpg
  memberOf: [rhdh-team, QE, Engineering]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh-team
  links:
    - url: https://dashboard.example.com
      title: Documentation
      icon: docs
    - url: https://dashboard.example.com
      title: JIRA
      icon: dashboard
    - url: https://dashboard.example.com
      title: GitHub
      icon: github
spec:
  type: product-area
  children: [Product-Manager, Engineering, UXD]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: UXD
spec:
  type: business-unit
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Product-Manager
spec:
  type: business-unit
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Engineering
spec:
  type: business-unit
  children: [Developers, QE]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Developers
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: QE
spec:
  type: team
  children: []